# Generated by Django 3.1.7 on 2021-04-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='software',
        ),
        migrations.AddField(
            model_name='software',
            name='features',
            field=models.ManyToManyField(related_name='software', to='software.Feature'),
        ),
    ]
