# Generated by Django 3.1.7 on 2021-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20210420_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareversion',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
