# Generated by Django 3.1.7 on 2021-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_auto_20210501_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='version',
        ),
        migrations.AddField(
            model_name='bug',
            name='version',
            field=models.ManyToManyField(related_name='bugs', to='software.SoftwareVersion'),
        ),
    ]
