# Generated by Django 3.1.7 on 2021-05-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0005_auto_20210501_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='user',
            new_name='reported_by',
        ),
    ]
