# Generated by Django 3.1.7 on 2021-05-20 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0007_bug_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_features', to='software.feature')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_features', to='software.softwareversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
