# Generated by Django 3.1.7 on 2021-05-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_requestfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeature',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_features', to='software.software'),
        ),
    ]
