# Generated by Django 3.1.7 on 2021-05-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0009_auto_20210520_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestfeature',
            old_name='features',
            new_name='feature',
        ),
    ]
