# Generated by Django 3.1.7 on 2021-05-20 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0010_auto_20210520_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_features', to='software.feature'),
        ),
        migrations.AlterField(
            model_name='requestfeature',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_features', to='software.software'),
        ),
        migrations.AlterField(
            model_name='requestfeature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='software.software'),
        ),
    ]
