# Generated by Django 3.1.7 on 2021-05-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0012_auto_20210520_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='latest_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_version', to='software.softwareversion'),
        ),
    ]
