# Generated by Django 3.1.7 on 2021-06-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0015_softwareversion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareversion',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
